# Generated by Django 2.2.5 on 2019-09-21 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='rating',
            field=models.IntegerField(default=5),
        ),
    ]
