# Generated by Django 2.2.5 on 2019-09-22 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20190921_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='rating',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='3', max_length=1),
        ),
    ]
