# Generated by Django 2.2.5 on 2019-09-22 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20190922_0836'),
    ]

    operations = [
        migrations.AddField(
            model_name='admodel',
            name='average_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='admodel',
            name='comments',
            field=models.IntegerField(default=0),
        ),
    ]
