# Generated by Django 2.2.5 on 2019-09-22 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20190922_0916'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admodel',
            old_name='average_rating',
            new_name='total_rating',
        ),
    ]
