# Generated by Django 2.2.5 on 2019-09-22 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogcommentmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='comments',
            field=models.IntegerField(default=0),
        ),
    ]
